apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: cluster-k3d-first
servers: 1
agents: 3
image: rancher/k3s:v1.31.5-k3s1

# (необязательно) если хочешь зафиксировать docker-сеть, укажи строкой:
# network: "k3d-cluster-k3d-first"

kubeAPI:
  hostPort: "6443"

volumes:
  - volume: "$PWD/Volume:/tmp/k3dvol:shared"
    nodeFilters:
      - server:*
      - agent:*

options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters: ["server:*"]
      - arg: "--disable=servicelb"
        nodeFilters: ["server:*"]
      - arg: "--disable=metrics-server"
        nodeFilters: ["server:*"]
      - arg: "--disable=network-policy"
        nodeFilters: ["server:*"]
      - arg: "--flannel-backend=none"
        nodeFilters: ["server:*"]
      - arg: "--disable=kube-proxy"
        nodeFilters: ["server:*"]
      # ← подсети задаём ТАК (а не через объект network):
      - arg: "--cluster-cidr=10.42.0.0/16"
        nodeFilters: ["server:*"]
      - arg: "--service-cidr=10.43.0.0/16"
        nodeFilters: ["server:*"]
      - arg: "--cluster-dns=10.43.0.10"
        nodeFilters: ["server:*"]